### ISSUE TITLE
Cancel Ascii Message if `--production` is used

### ISSUE THREAD

**Issue by TrevorJTClarke** [opencollective/opencollective-cli#5]
Hello! I've been using packages that use this CLI tool.
I love what can be accomplished with this!

Main issue:
* When deploying with CI/CD users (npm cmds) need to use `|| exit 0` or `|| true` to continue pipeline.
* Full Command: `opencollective postinstall || exit 0`
* Npm Command Example: `npm install --production`
* NOTE: This is *not* breaking anything, just seems like a bad UX to have this CLI running during production deploys. Mostlikely they wont even see it on CI/CD, but development mode would be just fine.

Our specific use:
* Nuxtjs
* ELB/Auto scaling group

I am filing issue here, as it could be an issue with other packages than nuxt. If you think differently, I'll send to them instead :)

**Comment by piamancini** [comment]
cc @xdamman @asood123

**Comment by xdamman** [comment]
adding the `|| exit 0` should be done on the side of the project.

We could update this package to not run on CI environment, it's a good idea. Just worried about doing any change that are not high priority given that quite a few packages depend on it and we may break them (that's why we just published a lightweight version on https://github.com/opencollective/opencollective-postinstall )
